zookeeper1:
  image: hieutrtr/docker-zookeeper:0.0.1
  ports:
    - "2181"
  links:
    - zookeeper2
	  - zookeeper3
zookeeper2:
  image: hieutrtr/docker-zookeeper:0.0.1
  ports:
    - "2181"
  links:
    - zookeeper1
	  - zookeeper3
zookeeper3:
	image: hieutrtr/docker-zookeeper:0.0.1
	ports:
	- "2181"
	links:
	- zookeeper1
	- zookeeper3
